spring:
  application:
    name: haeyo-back

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "change-this-secret-key-change-this-secret-key"
  expire-time: 3600000
